[build-system]
requires = ["flit_core >=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "cryoswath"
version = "0.2.2.post4"
authors = [
  { name="Jan Haacker", email="j.m.haacker@tudelft.nl" },
]
description = "Swath processing toolbox for CryoSat-2"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
keywords = ["glacier", "altimetry", "swath", "cryosat"]
dependencies = [
    "Bottleneck>=1,<2",
    "dask",
    "defusedxml",
    "geopandas>=1.0.1,<2",
    "gitpython>=3,<4",
    "h5netcdf>=1,<2",
    "h5py>=3,<4",
    "matplotlib>=3,<4",
    "numpy>=2,<3",
    "packaging>=24,<25",
    "pandas>=2,<3",
    "pyarrow>=19,<20",
    "pyogrio",
    "pyproj>=3,<4",
    "tables>=3,<4",
    "python-dateutil>=2,<3",
    "rasterio>=1,<2",
    "rioxarray",
    "scikit-learn>=1,<2",
    "scipy>=1,<2",
    "shapely>=2,<3",
    "statsmodels",
    "tqdm>=4,<5",
    "xarray<2025",
    "zarr>=2,<3",
]

[project.license]
file = "LICENSE.txt"
# ... = "MIT"

[project.optional-dependencies]
dev = ["black", "sphinx", "sphinx-rtd-theme"]
notebooks = ["ipykernel"]

[project.urls]
Repository = "https://github.com/j-haacker/cryoswath.git"
Documentation = "https://cryoswath.readthedocs.io/"
Issues = "https://github.com/j-haacker/cryoswath/issues"

[project.scripts]
cryoswath-init = "cryoswath.misc:init_project"

[tool.pytest.ini_options]
pythonpath = ["."]
